apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer-pod
  template:
    metadata:
      labels:
        app: tripviewer-pod
    spec:
      containers:
      - name: tripviewer
        image: registrytzs2899.azurecr.io/tripviewer:0.0.1
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: SQL_SERVER
          value: "sqlservertzs2899.database.windows.net"
        - name: SQL_USER
          value: "sqladmintZs2899"
        - name: SQL_PASSWORD
          value: "lQ9yh5Oy4"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.default.svc.cluster.local"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.default.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  selector:
    app: tripviewer-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80