apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
  labels:
    app: trips-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-pod
  template:
    metadata:
      labels:
        app: trips-pod
    spec:
      containers:
        - name: trips
          image: registrytzs2899.azurecr.io/trips:v0.0.1
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /api/trips/healthcheck
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/trips/healthcheck
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: SQL_SERVER
              value: "sqlservertzs2899.database.windows.net"
            - name: SQL_USER
              value: "sqladmintZs2899"
            - name: SQL_PASSWORD
              value: "lQ9yh5Oy4"
            - name: SQL_DBNAME
              value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  selector:
    app: trips-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
