apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  labels:
    app: user-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java-pod
  template:
    metadata:
      labels:
        app: user-java-pod
    spec:
      containers:
      - name: user-java
        image: registrytzs2899.azurecr.io/user-java:v0.0.1
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/user-java/healthcheck
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/user-java/healthcheck
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: SQL_SERVER
          value: "sqlservertzs2899.database.windows.net"
        - name: SQL_USER
          value: "sqladmintZs2899"
        - name: SQL_PASSWORD
          value: "lQ9yh5Oy4"
        - name: SQL_DBNAME
          value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  selector:
    app: user-java-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80